version: 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk-8:stretch
    steps:
      - checkout
      - run: ./mvnw test

workflows:
  version: 2

  build-then-test:
    jobs:
      - build